server:
  port: 8087

spring:
 cloud:
   gateway:
     routes:
       - id: retailer-services
         uri: http://localhost:8282
         predicates:
           - Path=/retailerservices/**
         filters:
           - AuthenticationFilter


       - id: retailer
         uri: http://localhost:8181
         predicates:
           - Path=/retailer/**
         filters:
           - AuthenticationFilter

       - id: location
         uri: http://localhost:8085
         predicates:
           - Path=/location/**
         filters:
           - AuthenticationFilter

       - id: customer
         uri: http://localhost:8082
         predicates:
           - Path=/customer/**
         filters:
           - AuthenticationFilter

       - id: identity-service
         uri: http://localhost:8086
         predicates:
           - Path=/auth/**


 application:
   name: GATEWAY

eureka:
  client:
    service-url:
      defaultZone : https://lavish-achievement-production.up.railway.app/